### ISSUE TITLE
Grundlegenden Rest-Server bauen

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#1]
Grundlegende Serveranwendung erstellen, welche mit Rest anzusprechen ist (Benötigt wahrscheinlich etwas Einarbeitung in Java Rest APIs

**Comment by alexlafleur** [comment]
Hey Leute, ich habe einen Basic Webservice gebaut, weiß aber nicht, wie ich den ins Git bekomme :( Kann mir jemand helfen? Das ist ein separates Projekt.

**Comment by leonbornemann** [comment]
Hey Alex;)
Um das bequem aus Eclipse heraus zu machen musst du unser Projekt von Github importieren und du brauchst das Egit Plugin für Eclipse.
Wenn du morgen in der Uni bist können wir das aber gerne gemeinsam machen (ich komme so gegen 14:00 vorbei)

**Comment by alexlafleur** [comment]
Hi Leon,

ich bin morgen leider nicht in der uni.. Aber ich schau mir das mal nochmal an mit dem Plugin, vllt schaff ich das auch so ;)

Mit Outlook für Android gesendet

On Sun, Jun 7, 2015 at 1:07 PM -0700, "leonbornemann" notifications@github.com wrote:
Hey Alex;)
Um das bequem aus Eclipse heraus zu machen musst du unser Projekt von Github importieren und du brauchst das Egit Plugin für Eclipse.
Wenn du morgen in der Uni bist können wir das aber gerne gemeinsam machen (ich komme so gegen 14:00 vorbei)

---

**Comment by leonbornemann** [comment]
Ok ich schreibs dir kurz die wesentlichen schritte:
1. Egit plugin installieren 
1.1 Bei dir git aufsetzen (falls noch nicht geschehen), gemeint ist der lokale ordner in dem git arbeitet
2. File -- import --> git --> Projects from git --> clone URI --> Github projekt url eingeben --> finish
3. Dann hast du das Projekt bei dir, erstell dir dann einfach ein passendes package, schieb da deinen code rein und dann kannst du über das Kontextmenü commiten/pushen

Hier ist ein ausführlicher Guide, da kannst du dir die für dich interessanten Schritte nochmal genauer nachlesen: http://www.vogella.com/tutorials/EclipseGit/article.html

**Comment by alexlafleur** [comment]
Der basic Webservice liegt jetzt in meinen Repository alexlafleur/Rest.
Ich war mir nicht sicher, ob ich das hier bei Leon reinpacken kann / darf, weil das ein separates Projekt ist.  Ich hoffe, ihr könnt drauf zugreifen!

**Comment by alexlafleur** [comment]
Mergen von REST Service und XMLProjekt vollständig. Wie der Service genutzt wird plus Einstellungen mit Server und co habe ich ins WIKI geschrieben
