### ISSUE TITLE
SPARQL Exploration

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#11]

**Comment by alexlafleur** [comment]
Also es erscheint mir so, dass die meisten Sprachen über "Sprache"+"_language" als Ressource erreichbar sind. Mit folgender Query kann man zB Longitude und Latitude von den Orten, in denen die Sprache gesprochen wird, extrahieren (ohne Leerzeichen):

SELECT \* WHERE {< http://dbpedia.org/resource/Chechen_language > dbpedia-owl:spokenIn ?spokenIn. 
?spokenIn dbpprop:latd ?latitude.
?spokenIn dbpprop:longd ?longitude}

Bei Sprachen mit Leerzeichen gibt es in der Regel Probleme, die Ressource automatisch zu erhalten, da sie unter einen anderen Namen in DBpedia gespeichert wurde oder gar nicht existiert (z.B. "Oromo (Harar)", "Jamul Tiipay").
Bei z.B. "Havasupai" ist mir aufgefallen, dass von Havasupai_language über den Browser zu Havasupai_dialect redirected wird. Da müssen wir mal schauen, ob das mit dem programmatischen Zugriff auch so ist.
@Infinituum (bist du Marcus??) Wäre cool, wenn du eine Methode bereitstellen könntest, die alle Languages extrahiert, dann kann ich mit Sparql schonmal testen, ob wir Daten für alle Languages bekommen und je nachdem können wir noch weiter aussortieren oder weiter entscheiden.

**Comment by alexlafleur** [comment]
Anscheinend gibt es auch unterschiedliche Properties für latitude und longitude. http://dbpedia.org/page/Lake_Turkana verwendet den namespace geo:lat, http://dbpedia.org/page/Chechnya hingegen dbpprop:latd

**Comment by leonbornemann** [comment]
Hey Alex, sorry ich bin bisher leider gar nicht dazu gekommen mich in die dbpedia einzuarbeiten, scheint so als hätte ich mir etwas viel vorgenommen, aber die dumme xslt transformation hällt mich echt ganz schön auf xD
Was du rausgefunden hast sieht ja aber schon gut aus, wie leicht kriegt man aus den Orten, bzw. longitude/lattitude das Land raus?

**Comment by leonbornemann** [comment]
Bezüglich Languages: Schau mal hier: src/data_exploration/DataExploration.java 
Wenn du die Main-Methode da ausführst müssten aus den Orginaldaten die verschiedenen Sprachen geprinted werden. Markus ist leider noch durch meine xslt-Verzögerungen geblockt (bzw. er kann die Sachen schon implementieren, aber resultate kann man leider noch nicht extrahieren :/

**Comment by alexlafleur** [comment]
Ich habe die Languagedaten aus DataExploration ausgelesen und in den SPARQL Endpoint geworfen. Dabei kam heraus, dass ca. 157 Sprachen in DBpedia nicht ansprechbar sind (weil sie z.B. Leerzeichen enthalten und Leerzeichen dürfen in einer SPARQL query nicht auftreten oder sie existieren einfach nicht in der Ontology) und ca. 46 Sprachen kann ich extrahieren mit Longitude und Latitude. Ich printe sie momentan einfach auf die Konsole, damit wir schonmal wissen, welche Sprachen aus den Daten gelöscht werden können, weil wir keine Extrainformationen erhalten.
