### ISSUE TITLE
Client Gui

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#14]
Folgendes muss gemacht werden:
-Welcome Screen:
          -Hintergrundbild
          -Logo mit Namen der Anwendung
          -Buttons

-Sentence Screen (Quiz)
          -Layout wie oben

**Comment by janles** [comment]
Ich pushe gleich ein großes Update bzgl. der GUI. 
Insgesamt haben wir nun eine Vielzahl an Technologien genutzt:
JQuery, CSS, HTML, JSP
Leider ist noch nicht alles so, wie ich mir das vorgestellt habe

Was noch gemacht werden muss:
-auf der ersten Seite müssen die Buttons noch beschriftet werden (ist nicht so leicht, wie man denkt)
-wenn man auf den button drückt (onmousedown), dann soll auch der Button optisch gedrückt werden (hab ich auch leider noch nicht hinbekommen, die passenden Bilder werden dazu gepusht)

Auf der zweiten Seite:
-dort sieht man derzeit nur eine Tabelle, diese muss noch entsprechend gefüllt werden
-um die Logik habe ich mich nicht gekümmert, es werden also keinerlei Fragen irgendwo eingetragen

Außerdem müssen wir noch klären wie genau die Auswertung der Antworten erfolgen soll. Dies ist bisher noch nicht umgesetzt worden.

**Comment by janles** [comment]
Alex und ich haben gestern und heute noch mehrere Sachen aktualisiert und verschönert. 
Bis auf ein paar Feinheiten sind die ersten beiden Seiten (Welcome + Fragenseite) soweit funktionstüchtig. Nur das Aussehen müsste noch ein wenig angepasst werden. Zudem hat Alex die Funktionalität hinzugefügt, dass die Sätze und Antworten variabel gefüllt werden können.
Für den offiziellen ersten Meilenstein sollte die Darstellung ausreichen.

TODO: Festlegen des Aussehens der Auswertung (bspw. direktes Anzeigen der korrekten Antwort oder alle Infos sammeln und zum Schluss anzeigen)

**Comment by janles** [comment]
Der Client ist nun so an sich fertig. Gern könnt ihr ihn euch angucken und ggf. Verbesserungen vorschlagen oder gleich selbst tätigen.
Das einzige was noch gemacht werden muss, ist das Verheiraten von Server und Client. 
Derzeit wird noch auf Testdaten gearbeitet.
