### ISSUE TITLE
Client Logik

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#15]
Auswertung der Antworten, etc...

**Comment by janles** [comment]
Der Client wurde nun so angepasst, dass man auf der Startseite einen Modus (5 Fragen oder 10 Fragen) auswählen kann. Die Anzahl der Fragen wird an die Logik gesendet, sodass nun die Logik nur noch an den Server die Anzahl weiterleiten muss. (In der Klasse QuestionDisplayer.java wurde die Methode um das Argument int numerOfQuestions erweitert.)

**Comment by janles** [comment]
Der Client wertet die Antworten nun direkt aus (Buttons werden rot bzw. grün) und merkt sich die korrekt abgegebenen Antworten. Siehe dazu Issue #14.

**Comment by alexlafleur** [comment]
Hi @javiergd, da jetzt noch kein Servlet da war, habe ich jetzt damit angefangen eins zu bauen. Ich bekomme leider bei der Umwandlung des XML zum XMLQuestion-Objekt eine Exception. Ich habe mir testweise das folgende Beispiel über den Rest-Service schicken lassen:

`<?xml version="1.0" encoding="UTF-8"?>
<languageExamples xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="questionsToClient.xsd">
im Ordner resources\XMLSchema QuestionsToClient\questionsToClientExample.xml

Er sagt mir "languageExamples" ist nicht bekannt als Tag. Wie funktioniert diese Umwandlungs-Methode??

Außerdem wird vom Server noch KEINE zufällige Frage gesendet, Leute! @leonbornemann @janles @Infinituum  An diejenigen, die die Server-Logik gebaut haben, baut das bitte in den Server ein, dass er die Fragen schickt :) Momentan wird unsere Auswahl an Fragennummern auch nicht verwertet. Ist die Frage: Machen wir das weg oder ändern wir nochmal den Server?

**Comment by leonbornemann** [comment]
Hi zusammen, ich treff mich morgen ab 10:00 mit Javier in der Uni, wer will kann ja dazustoßen
Die Server-Logik generiert auf jeden Fall Random Fragen, das Schicken ist ja Sache der Rest-Schnittstelle und die werden wir uns morgen dann nochmal vornehmen anscheinend gibts da noch Probleme wenn das ganze im war-file ausgeführt wird.
Apropos war-File: Was brauche ich nochmal um den Server auszuführen Java EE und sonst noch was? :)
