### ISSUE TITLE
Sprach-Anreicherungsdatenbank erstellen

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#17]
Infos aus Sparql in extra DB

**Comment by alexlafleur** [comment]
@leonbornemann Das XML file mit angereicherten Daten steht. Ich habe eine Methode in "DataExtraction" hinzugefügt, die die DB einfach mal anspricht. Ist die Schnittstelle schon fertig für die Nutzung der DB? Übernimmst du das?

**Comment by leonbornemann** [comment]
Hallo Alex, die Schnittstelle für die Nutzung der DB müsste von Markus inzwischen online sein. Ich schaue gleich mal ins Projekt und schau Mal ob ich schonmal eine grundlegende Logik-Klasse bauen kann :)

**Comment by leonbornemann** [comment]
@alexlafleur Ah jetzt erinnere ich mich erst was du meinst, klar ich baue um deine extra-info Datenbank eine Schnittstelle. Momentan einzig von mir geplante Methode dafür ist: 
public ExtraInfo getExtraInfo(String language)
oder fällt dir sonst noch was ein, was dort reinmüsste?
