### ISSUE TITLE
Konzept für Eigene Daten (Wahrscheinlich Quizfragen)

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#2]
Wir müssen uns überlegen wie unsere Quizfragen aussehen können (benötigt wahrscheinlich weiter Daten-Exploration). Dann brauchen wir für unsere Fragen ein XML-Schema.

**Comment by leonbornemann** [comment]
Brauchen XML-Schema für Fragen/Antworten, wenn Client-Anwendung vorhanden ist, da diese dann XML-Daten verarbeiten müssen, das entfällt, wenn der Server nur html rausschickt

**Comment by janles** [comment]
Fragen:
1. Wird im XML-Dokument, welches an den Client gesendet wird nur jeweils eine einzige Frage gesendet?
   Vorstellbar wäre: 
   a) Es wird immer nur eine Frage nach der nächsten gesendet.
   b) Wir senden auf einmal bspw. 10 Fragen in denen die korrekte Antwort gleich enthalten ist. Vorteil: Wir müssten rein theroetisch, wenn wir einen Client haben, nur maximal 2x mit dem Server kommunizieren. Einmal, um die Fragen zu bekommen und zum Schluss, um das Gesamtergebnis zum Server zu schicken (weil wir ja eine Art Highscore machen wollen).
2. Wir wollen zusätzlich zur Sprache des Fragesatzes Informationen mitsenden (bspw. von welchem Land die Sprache eine offizielle Sprache ist). Hier würde ich die Anzahl der Länder auf 2-4 beschränken. Zur Sprache Deutsch gibt es bereits 8 Länder (bzw. Provinzen etc).

**Comment by leonbornemann** [comment]
Da der Vorteil rein preformance-technisch auffallen würde, würde ich sagen, dass das erstmal egal ist und wir das so machen sollten wie es einfacher ist. Alle Fragen auf einmal schicken bedeutet mehr Logik im Client, Fragen nacheinander schicken bedeutet mehr verwaltungsaufwand im server. Keine Ahnung was da einfacher ist, wahrscheinblich erstmal ersteres?

**Comment by leonbornemann** [comment]
@ 2. das wird dann relevant, wenn wir wissen, wie viel wir mit sparql an Daten aus der dbpedia kriegen, oder?

**Comment by janles** [comment]
Das Schema mit einer Beispieldatei liegt unter XML-Project/resources/XMLSchema QuestionsToClient/
Ergebnis muss noch besprochen/abgenommen werden.

**Comment by janles** [comment]
Heute mit Leon besprochen und abgenommen.
Es wurden noch kleine Änderungen vorgenommen und hochgeladen.
