### ISSUE TITLE
SVG Vektorgrafik anschauen (für Karten-darstellung)

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#23]

**Comment by Infinituum** [comment]
Hab eine gut brauchbare SVG gefunden, in der jedes Land für jedes Element als title definiert ist. Verwenden darf man es auch, solange die Quelle halt angegeben wird. Hier mal ein Link dazu: http://www.amcharts.com/svg-maps/?map=world
Die Elemente bestehen aus id, title, class und einer Ansammlung von Längen- und Breitengraden und lassen sich wohl recht einfach färben. ( style="fill:red" in ein Element einfügen reicht zB um unsere Rotfärbung zu bekommen)
