### ISSUE TITLE
Encoding "?" bei Serverübertragung

### ISSUE THREAD

**Issue by alexlafleur** [leonbornemann/XML-Project#29]

**Comment by javiergd** [comment]
Wie ich schon fürchtete, die '?' die in einige Beispielsätze auftauchen sind keine UTF-8 Symbole. Das heißt, die können nicht zum Client übertragen werden.
Die Frage ist nun, ob es einen möglichen bzw. schnellen Workaround gibt, damit diese Fragen nicht so hässlich aussehen.

Wenn jemand eine Idee hat, bitte meldet sich! (wir können ja diese Fragezeichen einfach weg lassen, aber dann würde die Frage auch nicht schön aussehen...)

**Comment by janles** [comment]
Wie ich vorgeschlagen habe, würde ich einfach ? und = aus den Fragen löschen. Zwar sind dann so an sich die Sätze "falsch", weil Zeichen fehlen, aber das ist besser als es derzeit ist.

**Comment by alexlafleur** [comment]
Habe die Zeichen aus dem Originalsatz gelöscht.

**Comment by leonbornemann** [comment]
Mit Orginalsatz meinst du den Satz, der beimn Client ankommt, oder? Also nicht die Orginaldaten?

**Comment by janles** [comment]
Ja, genau. Aber anscheinend hat Javier das jetzt auch schon serverseitig angepasst.

**Comment by leonbornemann** [comment]
ok, naja doppelt hält besser xD
