### ISSUE TITLE
Bugfix: Warum wird Russia / United States manchmal nicht eingefärbt

### ISSUE THREAD

**Issue by alexlafleur** [leonbornemann/XML-Project#30]

**Comment by janles** [comment]
@alexlafleur Nach deinem Update von gestern werden bei mir nur beim erstmaligem Anzeigen der SVG die Länder angezeigt. Danach ist auch die Karte wieder klein.

**Comment by alexlafleur** [comment]
@janles Das konnte ich bei mir nicht reproduzieren... Was hast du denn genau nacheinander geklickt, dass dieses Verhalten auftritt? Bei mir werden die Länder jedes Mal eingefärbt....
Hat jemand anders dasselbe Problem?

**Comment by janles** [comment]
@alexlafleur Welchen Browser benutzt du denn, auch FF, oder?
Ich habe nun herausgefunden, dass er (warum auch immer) nicht darauf wartet bis der DOM Tree komplett geladen wurde. (Jedenfalls nicht bei mir.)
Das passiert aber nicht immer. Also ab und zu färbt er mir tatsächlich auch die Länder ein, aber meistens eben nicht.
Im FF gibt es per F12 die Konsole. Dort steht bei mir ab und zu "TypeError: a.getElementById is not a function scripts.js:99:18" 
Außerdem kann ich erkennen (wenn man oben links auf "Netz" klickt), dass wenn die Grafik per GET nicht geholt wird, auch dieser Fehler auftritt. 
Sobald ein GET Eintrag mit der SVG auftaucht, dann ist alles super.

Es kann sein, dass Alex den Fehler nicht bekommt, weil ihr Rechner langsamer ist und daher mehr Zeit zum Laden der kompletten Seite hat. Keine Ahnung. Wäre nur ne Idee.

**Comment by janles** [comment]
Bevor ich hier jetzt noch mehr Zeit investiere, bei wem läuft es denn ohne Probleme? 
Wir brauchen eine funktionsfähige Version zum Zeigen. Alex und ich fallen da dann erstmal raus. Wer würde am Mittwoch den Laptop mit einer vollständig laufenden Version mitbringen?

**Comment by leonbornemann** [comment]
Hmm was ist jetzt der Status? Das einfärben der Grafik macht manchmal probleme, aber bei Alex geht es?

**Comment by leonbornemann** [comment]
Ich bin morgen btw in der Uni also wenn noch was ist können wir uns auch gerne treffen

**Comment by janles** [comment]
Genau, Leon.
Wäre eben totaaaaal super, wenn das mal jmd. Anderes testen würde. Sonst wirds vermutlich nicht gehen am Mittwoch.

**Comment by leonbornemann** [comment]
Hmm ich könnte jetzt demnächst los - wann seid ihr denn da?

**Comment by leonbornemann** [comment]
bzw. seid ihr überhaupt da? :)

**Comment by janles** [comment]
Sind bis 14 Uhr in einer VL.

**Comment by leonbornemann** [comment]
Gut treffen wir uns um 14:00 im Foyer?

**Comment by alexlafleur** [comment]
Hast du bei dir jetzt alles aufgesetzt? Sprich java ee, server und die neusten Versionen? Wenn nicht, kümmern Jan und ich uns morgen darum. Würden uns jetzt nur treffen, um zu gucken, ob es bei dir funktioniert oder nicht.

On Mon, Jul 6, 2015 at 1:35 AM -0700, "leonbornemann" notifications@github.com wrote:
Gut treffen wir uns um 14:00 im Foyer?

---

**Comment by leonbornemann** [comment]
Java EE ist jetzt runtergeladen, ausgeführt hab ichs noch nicht, aber da ich eh in die uni wollte um was für den vortrag zu amachen können wir dann sehn ob alles geht

**Comment by alexlafleur** [comment]
Ok, kannst du das dann schonmal so vorbereiten, dass wir das dann gleich ausprobieren können? Sehen uns dann im 14 Uhr im Foyer. :)

On Mon, Jul 6, 2015 at 2:19 AM -0700, "leonbornemann" notifications@github.com wrote:
Java EE ist jetzt runtergeladen, ausgeführt hab ichs noch nicht, aber da ich eh in die uni wollte um was für den vortrag zu amachen können wir dann sehn ob alles geht

---

**Comment by leonbornemann** [comment]
Alarm!! xD Ich habe noch ein bisschen gespielt und auch ein paarmal den Fehler bekommen, dass manche Länber nicht angezeigt werden - kann es eventuell daran liegen, dass manche Ländernamen unterschiedlich sind (also die aus der DBPedia vs die aus der .svg) ? - ich versuche mal zu verifizieren, dass es immer die gleichen Länder sind, die nicht angezeigt werden

**Comment by janles** [comment]
Kannst du dir sparen. Manche Länder gibt es tatsächlich nicht in der SVG. Solange es nicht passiert, dass du ein unterschiedliches verhalten bei gleichen Ländern bekommst, ist es normal. Ich meine: bspw.  Wird russia immer markiert und alor Island nicht, ist alles gut.

**Comment by leonbornemann** [comment]
Achso das war nen ganz anderer bug, der bei dir aufgetreten ist?
Dass manche Länder nichtdrin sind ist zwar Schade lässt sich aber schwer ändern

**Comment by leonbornemann** [comment]
Bisher habe ich kein inkosistentes Verhalten gefunden

**Comment by alexlafleur** [comment]
Bug fixed!
