### ISSUE TITLE
!!!!!Testing!!!!!

### ISSUE THREAD

**Issue by alexlafleur** [leonbornemann/XML-Project#32]

**Comment by javiergd** [comment]
Hallo allerseits, ich habe gerade unser Client getestet und habe bemerkt, dass wahrscheinlich die letzte Antwort wird nicht im Summary gezeigt (obwohl ich 5 Mal die richtige Antwort gewählt hatte, die Summary Seite zeigte immer 4 out of 5  richtig beantwortete Fragen). Also wie gesagt ich vermute, dass die Antwort zur letzter Frage nicht gespeichert wird.

Ausserdem zeigt bei mir die SVG Karte keine gefärbte Länder, aber das konnte ja auch an meinem Browser liegen.

Ansonsten habe ich keine weitere Probleme erkennt :)

**Comment by janles** [comment]
Ich habe den Bug, dass die letzte Frage nicht als "korrekt" ausgewertet wird, behoben.
Bei mir werden die Länder eingefärbt.

**Comment by janles** [comment]
Ich habe die randomisierten Buttons hinzugefügt. Das klappt nach meinen ersten Tests sehr gut. Bitte testet das einmal nach. Über "Element untersuchen" bekommt ihr auch unter der Variable "correctAnswer" die richtige Antwort heraus und könnt sie auswählen.

Leider habe ich anscheinend einen neuen Fehler eingebaut bzw, wiederentdeckt. -.- Wenn ich den Client das erste Mal ausführe über die URL (also NUR nach dem WAR-Export und direktem Ausführen), bekomme ich eine NPE. (@alexlafleur: Ich denke das ist der Fehler, den wir vorhin hatten und der dann plötzlich verschwunden ist.) Genau tritt der Fehler nach der Wahl von "5 Sentences" auf. Wollt ihr weitertesten, dann aktualsiert die Seite einfach, dann gehts. Ich gucke mir den Fehler morgen nochmal an.

**Comment by janles** [comment]
Habe den NPE behoben. Man sollte nicht auf die Fragen zugreifen, wenn sie noch nicht da sind -.-

**Comment by janles** [comment]
#33 Meine Tests der automtischen Anpassung der Textgröße auf Buttons ist soweit gut verlaufen. Bitte schreibt hier die Sprachen rein, die immer noch nicht auf den Button passen. (North Swedish (location uns...)) passt meiner Meinung nach auf den Button. Der Umbruch ist zwar blöd, aber der Text passt.

**Comment by javiergd** [comment]
Bitte auch testen, ob immer noch Wiederholungen beim Fragen Auswahl auftauchen.

**Comment by javiergd** [comment]
@janles ich habe soweit keine Sprachen erkennt, die nicht auf den Button passen, gut gemacht! :+1:

**Comment by janles** [comment]
Bitte noch einmal abschließend für morgen testen, ansonsten ist alles fertig, deshalb schließe ich den Issue jetzt.
