### ISSUE TITLE
Abgabe vorbereiten (konfigurierbarer Port)

### ISSUE THREAD

**Issue by janles** [leonbornemann/XML-Project#35]
Wie angemerkt wurde, sollten wir den Port 8080 nicht standartmäßig belegen. Wie können wir das konfigurierbar machen?

**Comment by alexlafleur** [comment]
Marko meinte doch, dass wir einfach angeben sollen, welcher port wurde verwenden, von daher würde ich mir da jetzt keine Gedanken darüber machen

**Comment by janles** [comment]
Ok, das hatte ich anders in erinnerung. Dann schließe ich das wieder.
