### ISSUE TITLE
XML-Schema für Sprach-Daten erstellen und alte Daten in neues Schema transformieren

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#6]

**Comment by janles** [comment]
Die XML Datein, die mit XSLT erstellt wurden und in den Verzeichnissen "example xslt output" & "resources" liegen, sind fehlerhaft. Wenn ich die XML-Validation ausschalte, dann sind die Fehler weg, aber wir sollten darauf achten keine fehlerhaften Datein hochzuladen. Bitte überprüfe das einmal. Danke

**Comment by leonbornemann** [comment]
UUps das kann durchaus sein, als ich die hochgeladen habt wusste ich noch nicht, dass fehlerhafte xmls compile-fehler werfen können. Sollte sich fixen, sobald die xslt-Transformation vollständig ist, was heute oder morgen der Fall sein sollte :)

**Comment by leonbornemann** [comment]
Wenn euch die korrupten xml-Files stören, löscht sie einfach, das sind eh nur Zwischenergebnisse, xslt-Transformation zieht sich leider noch etwas hin, Xalan (also der xslt-Prozessor) scheint einen Fehler mit Unicode zu haben, ich muss mal herausfinden, ob das stimmt und falls ja umsteigen -.-
