### ISSUE TITLE
Dummy-Client erstellen

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#7]
Dummy Client, der den grundlegenden Server nutzt

**Comment by janles** [comment]
Ich habe nun einen Dummy Client erstellt. 
Hier kurz die Zusammenfassung:
-eigenständiges Projekt (ebenfalls Web Project und daraus wird ein WAR-File erstellt)
-Dummy Client läuft zusammen mit dem Server auf einer Maschine (muss aber nach jetziger Implementierung nicht zwangsweise so sein)
-der Client sendet einen request an den Server und gibt die Antwort auf dem Server aus

Der Client kann bisher auch noch nichts weiter. (Die Logik muss noch implementiert werden.)
Wie sollen wir mit diesem Extra-Projekt umgehen? Eventuell wäre Maven wohl eine Lösung.
@javiergd Hast du eine andere Idee oder den Client anders erstellt?
