### ISSUE TITLE
einheitliches XML-Layout festlegen

### ISSUE THREAD

**Issue by janles** [leonbornemann/XML-Project#8]
Festlegen des Aufbaus unserer XML-Dateien. Sollen Informationen als Inhalt von Elementen oder als Attribute von Elementen gespeichert werden?

Vorschlag: 
Wir halten uns an den Aufbau der XML-Dateien der Datenquelle.
Sprich: Dort werden ausschließlich Informationen als Inhalt von Elementen dargestellt.

**Comment by leonbornemann** [comment]
Hmm alles was definitiv keine Unterelemente mehr kriegt kann theoretisch auch als attribut gespeichert werden (ist dann übersichtlicher)
Ansonsten halt Elemente für alles was noch extra Informationen bekommen könnte.
Wir können uns da gerne erstmal an die Ausgangsstruktur halten.
