### ISSUE TITLE
XML-Schema für eigene Datendarstellung, sowie 1-2 selbstgebaute Beispieldateien erzeugen

### ISSUE THREAD

**Issue by leonbornemann** [leonbornemann/XML-Project#9]
Wie besprochen übernimmt das Jan

**Comment by janles** [comment]
Vorlage: http://pad.spline.de/rYWXHuLpdl

**Comment by janles** [comment]
Ich habe gerade festgestellt, dass die gegebenen Daten (sprich die XML Dateien der Datenquelle) eigentlich nicht valide sind. Sie enthalten Sonderzeichen, wie z.B. ä. Diese können wir aber nicht einfach so in unsere Datenbank speichern, denn dies lässt unser XML Schema nicht zu. D.h. wir müssen alle Sonderzeichen (vermutlich aus jeder Sprache) erstmal umwandeln.
Oder gibt es da eine andere Möglichkeit? Ich habe jedenfalls nicht passendes gefunden.

**Comment by janles** [comment]
Dateien unter XML-Project/resources/XMLSchema DataRepresentation abgelegt.

**Comment by leonbornemann** [comment]
Todo: Schema-Validierug (Umlaute?)

**Comment by janles** [comment]
Anscheinend hat sich das Problem nun von "allein" gelöst. In eclipse läuft die Validierung ohne Probleme durch. 
Ich habe den letzten Stand gepusht und nun schließe ich den Issue.
